DROP DATABASE IF EXISTS Juego;
CREATE DATABASE Juego;

USE Juego;

CREATE TABLE JUGADOR(
	NICK VARCHAR(30) NOT NULL,
	PASWORD VARCHAR(30) NOT NULL,
	PRIMARY KEY (NICK)	 
)ENGINE= InnoDB;

CREATE TABLE PARTIDA(
	ID INT NOT NULL,
	CIUDAD VARCHAR(30) NOT NULL,
	GANADOR VARCHAR(30) NOT NULL,
	FECHA VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (GANADOR) REFERENCES JUGADOR (NICK)
)ENGINE= InnoDB;

CREATE TABLE PUNTUACIONES(
	PLAYER VARCHAR(30),
	IDPARTIDA INT,	
	PUNTOS INT,
	FOREIGN KEY (PLAYER) REFERENCES JUGADOR (NICK),
	FOREIGN KEY (IDPARTIDA) REFERENCES PARTIDA (ID)
)ENGINE= InnoDB;

INSERT INTO JUGADOR VALUES('Juan','Contra1');
INSERT INTO JUGADOR VALUES('Pedro','Contra2');
INSERT INTO JUGADOR VALUES('Sara','Contra3');
INSERT INTO JUGADOR VALUES('Bryan','Contra4');
INSERT INTO JUGADOR VALUES('Michelle','Contra5');

INSERT INTO PARTIDA VALUES(1,'Barcelona','Juan','30/03/2021');
INSERT INTO PARTIDA VALUES(2,'Barcelona','Sara','19/03/2021');
INSERT INTO PARTIDA VALUES(3,'Barcelona','Sara','25/03/2021');

INSERT INTO PUNTUACIONES VALUES('Juan',1,5);



